-- Synthetic fixture generated by the previous backend. No real user data.
BEGIN TRANSACTION;
CREATE TABLE rate_limits (
    key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL
  );
CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires INTEGER NOT NULL
  );
INSERT INTO "sessions" VALUES('ffe054fe7ae0cb6dc65c3af9b61d5209f439851db43d0ba5997337df154668eb',1,4102444800000);
INSERT INTO "sessions" VALUES('a0fab1377f49a759b57f63318262ebe89fabfc990e8e93ceac2984561482b9d4',2,4102444800000);
CREATE TABLE shipments (
    id TEXT PRIMARY KEY, name TEXT NOT NULL, carrier TEXT NOT NULL, reason TEXT NOT NULL,
    device TEXT NOT NULL, tracking TEXT NOT NULL, shipped TEXT NOT NULL, arrived TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1, created TEXT NOT NULL,
    creator INTEGER NOT NULL REFERENCES users(id), updater INTEGER NOT NULL REFERENCES users(id)
  );
INSERT INTO "shipments" VALUES('12345678-1234-1234-1234-123456789abc','Synthetic migration example','DHL','Offboarding','TEST-DEVICE','TEST-TRACKING','2026-09-15','',3,'2026-09-21T09:00:00.000Z',1,2);
CREATE TABLE users (
    id INTEGER PRIMARY KEY CHECK(id IN (1,2)), email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    password_hash TEXT NOT NULL, created TEXT NOT NULL
  );
INSERT INTO "users" VALUES(1,'one@example.test','1a1d693ca7495ed2e3f84e84a75931c9:ab48d0513da8253cea062ceacd5844c82f211f77c508eda06faa7afd298b26e1d0028744ee5a33806e14b39db6b1d21b0304ba24c6376a6d83884eb74af3f4a6','2026-09-21T09:00:00.000Z');
INSERT INTO "users" VALUES(2,'two@example.test','b9fee23571be0f6888c456867e6f7ebb:77653ef72aef0d6fc95752ffa26f513f94bf92a6ffc843cb06b82479e06c193d74c5f752e85818a02cc4e7340b856a5e275d8d069baddd183e19569b19bef405','2026-09-21T09:00:00.000Z');
CREATE INDEX sessions_user ON sessions(user_id);
CREATE INDEX shipments_created ON shipments(created);
COMMIT;
