import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeftRight, LockKeyhole, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import ReturnDesk from './return-desk';
import './styles.css';
type User={email:string};
async function request(path:string,body?:unknown){
 const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const data=await r.json().catch(()=>({error:'Verbindung unterbrochen. Bitte erneut versuchen.'})) as {error?:string;user:User;configured:boolean};
 if(!r.ok)throw new Error(data.error||'Die Anfrage ist fehlgeschlagen.');return data;
}
function App(){
 const [user,setUser]=useState<User|null>(null),[mode,setMode]=useState<'loading'|'login'|'setup'>('loading'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[email2,setEmail2]=useState(''),[password2,setPassword2]=useState('');
 const [passwordOpen,setPasswordOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[passwordError,setPasswordError]=useState('');
 async function load(){setMode('loading');setError('');try{const response=await fetch('/api/auth/me',{cache:'no-store'});if(response.ok){const data=await response.json() as {user:User};setUser(data.user);setMode('login');return;}if(response.status!==401)throw new Error('Verbindung fehlgeschlagen. Bitte erneut versuchen.');const setup=await request('/api/setup');setMode(setup.configured?'login':'setup');}catch(e){setMode('login');setError((e as Error).message);}}
 useEffect(()=>{void load();const expired=()=>{setUser(null);setMode('login');setPasswordOpen(false);setPassword('');setNotice('Deine Sitzung ist abgelaufen. Bitte erneut anmelden.');};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired);},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{
  if(mode==='setup'){await request('/api/setup',{token,users:[{email,password},{email:email2,password:password2}]});setMode('login');setPassword('');setPassword2('');setToken('');setNotice('Beide Konten sind eingerichtet. Du kannst dich jetzt anmelden.');}
  else{const data=await request('/api/auth/login',{email,password});setUser(data.user);setPassword('');}
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){if(busy)return;setBusy(true);try{await request('/api/auth/logout',{});setUser(null);setPassword('');setPasswordOpen(false);setNotice('Du bist abgemeldet.');}catch{setPasswordError('Abmelden fehlgeschlagen. Bitte erneut versuchen.');setPasswordOpen(true);}finally{setBusy(false);}}
 async function changePassword(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setPasswordError('');try{await request('/api/auth/password',{currentPassword,newPassword});setCurrentPassword('');setNewPassword('');setPasswordOpen(false);}catch(e){setPasswordError((e as Error).message);}finally{setBusy(false);}}
 if(mode==='loading')return <div className="auth-page"><div className="auth-card" role="status"><LoaderCircle className="spin"/><p>IBM@Return wird geladen …</p></div></div>;
 if(user)return <><ReturnDesk onLogout={()=>void logout()} onPassword={()=>{setPasswordError('');setPasswordOpen(true);}} email={user.email}/><Dialog open={passwordOpen} onOpenChange={v=>{if(!busy){setPasswordOpen(v);setCurrentPassword('');setNewPassword('');}}}><DialogContent className="entry-dialog"><DialogHeader><DialogTitle>Passwort ändern</DialogTitle><DialogDescription>Verwende mindestens 12 Zeichen. Andere angemeldete Geräte werden abgemeldet.</DialogDescription></DialogHeader><form className="auth-form" onSubmit={changePassword}><div className="field"><Label htmlFor="current-password">Aktuelles Passwort</Label><Input id="current-password" type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} maxLength={128} required disabled={busy}/></div><div className="field"><Label htmlFor="new-password">Neues Passwort</Label><Input id="new-password" type="password" autoComplete="new-password" minLength={12} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required disabled={busy}/></div>{passwordError&&<p role="alert" className="form-error">{passwordError}</p>}<Button type="submit" disabled={busy}>{busy?'Speichert …':'Passwort speichern'}</Button></form></DialogContent></Dialog></>;
 return <main className="auth-page"><div className="auth-brand"><span className="brand-icon"><ArrowLeftRight size={22}/></span><span>IBM<span>@Return</span></span></div><section className={'auth-card '+(mode==='setup'?'setup-card':'')}><div className="dialog-icon"><LockKeyhole size={23}/></div><h1>{mode==='setup'?'Euren Arbeitsbereich einrichten':'Willkommen zurück.'}</h1><p className="auth-description">{mode==='setup'?'Lege die zwei Konten für eure gemeinsame Rücksendungsliste an.':'Melde dich an, um eure Rücksendungen zu verwalten.'}</p><form onSubmit={submit} className="auth-form"><fieldset disabled={busy}>
  {mode==='setup'&&<div className="field"><Label htmlFor="setup-token">Einrichtungsschlüssel</Label><Input id="setup-token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} minLength={32} required/><p className="auth-hint">Der einmalige Schlüssel aus der Hosting-Einrichtung.</p></div>}
  {mode==='setup'&&<h2 className="setup-heading">Dein Konto</h2>}
  <div className="field"><Label htmlFor="email">E-Mail-Adresse</Label><Input id="email" type="email" autoComplete="username" placeholder="name@beispiel.de" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required/></div><div className="field"><Label htmlFor="password">Passwort</Label><Input id="password" type="password" autoComplete={mode==='setup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==='setup'?12:undefined} maxLength={128} required/>{mode==='setup'&&<p className="auth-hint">Mindestens 12 Zeichen.</p>}</div>
  {mode==='setup'&&<><h2 className="setup-heading">Konto deines Kollegen</h2><div className="field"><Label htmlFor="email2">E-Mail-Adresse</Label><Input id="email2" type="email" autoComplete="off" value={email2} onChange={e=>setEmail2(e.target.value)} maxLength={254} required/></div><div className="field"><Label htmlFor="password2">Startpasswort</Label><Input id="password2" type="password" autoComplete="new-password" value={password2} onChange={e=>setPassword2(e.target.value)} minLength={12} maxLength={128} required/><p className="auth-hint">Mindestens 12 Zeichen. Dein Kollege kann es nach der Anmeldung ändern.</p></div></>}
 </fieldset>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="auth-notice" role="status">{notice}</p>}<Button className="auth-submit" type="submit" disabled={busy}>{busy?<><LoaderCircle size={17} className="spin"/> Bitte warten …</>:mode==='setup'?'Zwei Konten einrichten':'Anmelden'}</Button></form><p className="auth-footnote">{mode==='setup'?'Die Einrichtung ist nur einmal möglich.':'Zugriff nur für die beiden eingerichteten Konten.'}</p></section><p className="auth-caption">Rechnerrücksendungen · DHL & FedEx</p></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
